version: "3.3"
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: my-db
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .docker/mysql.env
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
  app:
    container_name: my-app
    environment:
      - TZ=America/Sao_Paulo
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    links:
      - db
    ports:
      - 80:80
      - 3000:3000
    working_dir: "/var/www"
    volumes:
      - ./www/fairtek-server:/var/www/fairtek-server
      - ./www/fairtek-portal/dist:/var/www/fairtek-portal
      - ./www/pm2.json:/var/www/pm2.json
    command: bash -c "script.sh"
volumes:
  my-db: {}
